Update Carousel Images
cwts-edu/cwts-web pull request #114
Opened 2024-01-05 16:05 UTC by Boonhub

Add BABC Banner and replace Christmas Banner

2024-01-05 19:12 UTC, saintfish requested changes

2024-01-05 19:12 UTC, saintfish commented on src/data/carousel.yml
> -  image: /images/carousel/christmas-eve-2023.jpg
Please delete the unused image files

2024-01-05 23:17 UTC, Boonhub commented on src/data/carousel.yml
> -  image: /images/carousel/christmas-eve-2023.jpg
Christmas banner image deleted

2024-01-06 19:26 UTC, saintfish commented on src/data/carousel.yml
> -  image: /images/carousel/christmas-eve-2023.jpg
Please delete it in this branch

2024-01-06 19:36 UTC, merged