Updtae 2024 Class schedule and calender
cwts-edu/cwts-web pull request #166
Opened 2024-08-14 21:29 UTC by Boonhub

Update 2024 Class schedule and 2024 Academic calendar

2024-08-17 17:10 UTC, saintfish requested changes

2024-08-17 17:10 UTC, saintfish commented on public/docs/course-schedules/Class-Schedule-2024-Fall.pdf
Why do we need to upload the pdf but there is no link to it?

2024-08-21 22:26 UTC, Boonhub commented on public/docs/course-schedules/Class-Schedule-2024-Fall.pdf
The PDF is the latest version dated 8/12 and there is a link [2024 秋季課程時間表] on that page.
![Class-schedule](https://github.com/user-attachments/assets/87c9062e-ee7f-4e25-b5c7-272a5b0c396d)

2024-08-24 17:23 UTC, saintfish approved these changes

2024-08-24 17:23 UTC, merged