Add MI to News
cwts-edu/cwts-web pull request #62
Opened 2023-07-05 23:29 UTC by martian523

Replace with new MI class

2023-07-06 04:17 UTC, saintfish requested changes

2023-07-06 04:17 UTC, saintfish commented on src/content/news/2023-04-15-mi-course.md
> -thumbnail: /images/news/2023基督教倫理-445x250.jpg
Please delete the unused image.

2023-07-06 04:17 UTC, saintfish commented on src/content/news/2023-04-15-mi-course.md
Please change the date in the filename.

2023-07-07 16:36 UTC, martian523 commented on src/content/news/2023-04-15-mi-course.md
Date changed.

2023-07-07 16:37 UTC, martian523 commented on src/content/news/2023-04-15-mi-course.md
> -thumbnail: /images/news/2023基督教倫理-445x250.jpg
I think I did?

2023-07-07 16:53 UTC, saintfish commented on src/content/news/2023-04-15-mi-course.md
> -thumbnail: /images/news/2023基督教倫理-445x250.jpg
Did you delete public/images/news/2023基督教倫理-445x250.jpg? Please check if you add the deletion to the commit

2023-07-07 19:02 UTC, martian523 commented on src/content/news/2023-04-15-mi-course.md
> -thumbnail: /images/news/2023基督教倫理-445x250.jpg
ok. just deleted it. so i have to delete all unused images from now on.

2023-07-07 19:43 UTC, saintfish commented on src/content/news/2023-04-15-mi-course.md
> -thumbnail: /images/news/2023基督教倫理-445x250.jpg
If you keep the habit to delete images in the change you delete the reference to them, just like this change, you will never have to clean up unused images.

2023-07-07 19:43 UTC, saintfish approved these changes

2023-07-07 19:44 UTC, merged